# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import todo_pb2 as todo__pb2


class TodoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUsers = channel.unary_unary(
        '/todo.TodoService/GetUsers',
        request_serializer=todo__pb2.UsersRequest.SerializeToString,
        response_deserializer=todo__pb2.UsersList.FromString,
        )
    self.GetUser = channel.unary_unary(
        '/todo.TodoService/GetUser',
        request_serializer=todo__pb2.User.SerializeToString,
        response_deserializer=todo__pb2.User.FromString,
        )
    self.GetUserTodos = channel.unary_unary(
        '/todo.TodoService/GetUserTodos',
        request_serializer=todo__pb2.User.SerializeToString,
        response_deserializer=todo__pb2.TodosList.FromString,
        )
    self.GetTodo = channel.unary_unary(
        '/todo.TodoService/GetTodo',
        request_serializer=todo__pb2.Todo.SerializeToString,
        response_deserializer=todo__pb2.Todo.FromString,
        )
    self.CreateTodo = channel.unary_unary(
        '/todo.TodoService/CreateTodo',
        request_serializer=todo__pb2.Todo.SerializeToString,
        response_deserializer=todo__pb2.Todo.FromString,
        )
    self.CreateUser = channel.unary_unary(
        '/todo.TodoService/CreateUser',
        request_serializer=todo__pb2.User.SerializeToString,
        response_deserializer=todo__pb2.User.FromString,
        )


class TodoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUsers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserTodos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUsers': grpc.unary_unary_rpc_method_handler(
          servicer.GetUsers,
          request_deserializer=todo__pb2.UsersRequest.FromString,
          response_serializer=todo__pb2.UsersList.SerializeToString,
      ),
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=todo__pb2.User.FromString,
          response_serializer=todo__pb2.User.SerializeToString,
      ),
      'GetUserTodos': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserTodos,
          request_deserializer=todo__pb2.User.FromString,
          response_serializer=todo__pb2.TodosList.SerializeToString,
      ),
      'GetTodo': grpc.unary_unary_rpc_method_handler(
          servicer.GetTodo,
          request_deserializer=todo__pb2.Todo.FromString,
          response_serializer=todo__pb2.Todo.SerializeToString,
      ),
      'CreateTodo': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTodo,
          request_deserializer=todo__pb2.Todo.FromString,
          response_serializer=todo__pb2.Todo.SerializeToString,
      ),
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=todo__pb2.User.FromString,
          response_serializer=todo__pb2.User.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'todo.TodoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
